#!/bin/bash
# Allan McAleavy 2017
# Login to Array and gather overall array stats
# Requires a DB called ARRAYS to be created.

user=<username>
pass=<password>
xiv=$1
stime=00
end=23
day=$2
month=$3
year=2017

mkdir ${xiv}_array
POST="http://<INFLUX_DB_SERVER>:8086/write?db=ARRAYS&precision=s"

# Get a list of hosts to parse.

/usr/bin/xcli -m $xiv -s -u $user -p $pass statistics_get start=${year}-${month}-${day}.0:${stime}:00 count=1440 resolution_unit=minute interval=1 > ${xiv}_array/${xiv}_${month}_${day}_${xiv}.csv

grep Time ${xiv}_array/${xiv}_${month}_${day}_${xiv}.csv
if [ $? = 0 ]
then
./graph_xiv_data.pl ${xiv}_array/${xiv}_${month}_${day}_${xiv}.csv Array > ${xiv}_array/array_batch
fi

cd  ${xiv}_array
/usr/bin/curl -i -XPOST ${POST} --data-binary @array_batch
cd ..
rm ${xiv}_array/${xiv}_${month}_${day}_${xiv}.csv
